image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Zammad
    init: ./init.sh
    command: |
      echo "Zammad prêt sur http://localhost:3000"

ports:
  - port: 3000
    onOpen: open-preview
  - port: 6379
    onOpen: ignore
