services:
  zammad:
    build:
      context: .
      dockerfile: Dockerfile.zammad
    ports:
      - "8080:3000"
    environment:
      RAILS_ENV: production
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: zammad-postgres
      DATABASE_NAME: zammad
      DATABASE_USER: zammad
      DATABASE_PASSWORD: zammad
      ELASTICSEARCH_HOSTS: http://zammad-elasticsearch:9200
      REDIS_URL: redis://redis:6379
    depends_on:
      - zammad-postgres
      - zammad-elasticsearch
      - redis
    command: >
      /bin/bash -c "
      pnpm install &&
      rails db:migrate &&
      rails assets:precompile &&
      rails server -b 0.0.0.0 -p 3000
      "

  zammad-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: zammad
      POSTGRES_PASSWORD: zammad
      POSTGRES_DB: zammad
    volumes:
      - zammad-postgres-data:/var/lib/postgresql/data

  zammad-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - zammad-elasticsearch-data:/usr/share/elasticsearch/data

  redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  zammad-postgres-data:
  zammad-elasticsearch-data:
  zammad-data:
