FROM zammad/zammad:latest

USER root

# Installer Node.js, npm, pnpm
RUN apt-get update && apt-get install -y curl gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g pnpm && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER zammad

WORKDIR /opt/zammad
