version: '3.8'

services:
  zammad-railsserver:
    image: zammad/zammad:latest
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - zammad-elasticsearch
      - zammad-database
    environment:
      RAILS_ENV: production
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: zammad-database
      DATABASE_NAME: zammad
      DATABASE_USER: zammad
      DATABASE_PASSWORD: zammad
      ELASTICSEARCH_HOSTS: http://zammad-elasticsearch:9200

  zammad-websocket:
    image: zammad/zammad-websocket:latest
    restart: always
    depends_on:
      - zammad-railsserver
    environment:
      RAILS_ENV: production

  zammad-database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: zammad
      POSTGRES_PASSWORD: zammad
      POSTGRES_DB: zammad
    volumes:
      - zammad-db-data:/var/lib/postgresql/data

  zammad-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - zammad-es-data:/usr/share/elasticsearch/data

volumes:
  zammad-db-data:
  zammad-es-data:
